# Generated by Django 4.2.1 on 2023-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_mobile_number_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_role', models.CharField(choices=[('HR', 'Male'), ('Manager', 'Manager'), ('Team Leader', 'Team Leader'), ('Python Developer', 'Python Developer')], default='Python Developer', max_length=20)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('emp_code', models.CharField(blank=True, max_length=70, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
